/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:61289013-25c2-4f44-9c0b-7bbf0fee444a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_pjJ6r1SOv",
    "aws_user_pools_web_client_id": "2ecncmcv5pd2coep5rls94u9t1",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://6cq34dvosrcybasbyppej4qj6u.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ukty3ncpu5haxp4724miubh3km"
};


export default awsmobile;
