/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:61289013-25c2-4f44-9c0b-7bbf0fee444a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_pjJ6r1SOv",
    "aws_user_pools_web_client_id": "2ecncmcv5pd2coep5rls94u9t1",
    "oauth": {}
};


export default awsmobile;
